/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void rollMethodWorks() {
        Library classUnderTest = new Library();
        boolean correctLength = false;
        boolean correctRange = true;
        int[] rollReturnVal = classUnderTest.roll(4);
        if (rollReturnVal.length == 4) correctLength = true;
        for (int el : rollReturnVal) {
            if (el < 1 || el > 6) correctRange = false;
        }
        if (correctLength && correctRange) System.out.println("works");
        else System.out.println("broken");
    }
    @Test void containsDuplicatesMethodWorks() {
        Library classUnderTest = new Library();
        int[] arr = {1 , 1 , 3};
        assertTrue(classUnderTest.containsDuplicates(arr), "containsDuplicates should return 'true'");
    }
    @Test void calcAveragesMethodWorks() {
        Library classUnderTest = new Library();
        int[] arr = {2, 3, 4};
        assertEquals(3, classUnderTest.calcAverages(arr), "calcAverages should return 3");
    }
    @Test void arrayOfArraysMethodWorks() {
        Library classUnderTest = new Library();
        int[][] arr = {
                {1,1,1},
                {2,2,2},
                {3,3,3}
        };
        int[] correctArr = {1,1,1};
        assertArrayEquals(correctArr, classUnderTest.arrayOfArrays(arr));
    }
}
