/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;
import java.util.Random;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {

    }

    public int[] roll(int n) {
        int[] newArr = new int[n];
        Random r = new Random();
        for (int i = 0; i < newArr.length; i++) {
            newArr[i] = r.nextInt(1, 7);
        }
        return newArr;
    }

    public boolean containsDuplicates(int[] arr) {
        int counter = 0;
        for (int i = 0; i < arr.length; i++) {
            for (int j = i + 1; j < arr.length; j++) {
                if (arr[j] == arr[i]) counter++;
            }
        }
        if (counter > 0) {
            return true;
        } else {
            return false;
        }
    }

    public double calcAverages(int[] arr) {
        double sum = 0;
        for (int el : arr) {
            sum += el;
        }
        return sum / arr.length;
    }

    public int[] arrayOfArrays(int[][] arr) {
        int[] lowestAvgArr = arr[0];
        for (int i = 0; i < arr.length; i++) {
            double avg = 0;
            double sum = 0;
            for (int j = 0; j < arr[i].length; j++) {
                sum += arr[i][j];
            }
            if (i == 0) {
                avg = sum / arr[i].length;
            } else if (avg > sum / arr[i].length) {
                avg = sum / arr[i].length;
                lowestAvgArr = arr[i];
            }
        }
        return lowestAvgArr;
    }

}

