/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void restaurantToStringWorks() {
        Restaurant classUnderTest = new Restaurant(4, "$$", "Da Riccardi");
        String correctOutput = "Da Riccardi\nprice:$$\nStars:4";
        assert(classUnderTest.toString().equals(correctOutput));
    }
    @Test void reviewToStringWorks() {
        Review classUnderTest = new Review(2, "Jeff", "solidly meh");
        String correctOutput = "Author:Jeff\n" +
                "Stars:2\n" +
                "solidly meh";
      assert(classUnderTest.toString().equals(correctOutput));
    }
    @Test void reviewIsAssociatedWithRestaurant() {
        Restaurant classUnderTest = new Restaurant(3, "$$$$", "Il SopraVValutato");
        Review gordonReview = new Review(1, "Gordon Ramsay", "Utter garbage");
        classUnderTest.addReview(gordonReview);
        assert(classUnderTest.reviews.size() == 1);
    }
    @Test void associatedReviewUpdatesRestaurantRating() {
        Restaurant classUnderTest = new Restaurant(0, "$$$$", "Il SopraVValutato");
        Review gordonReview = new Review(1, "Gordon Ramsay", "Utter garbage");
        classUnderTest.addReview(gordonReview);
        assert(classUnderTest.stars == 1);
    }
    @Test void alreadyAssociatedReviewDoesNotUpdateRestaurantRating() {
        Restaurant classUnderTest = new Restaurant(0, "$$$$", "Il SopraVValutato");
        Review gordonReview = new Review(1, "Gordon Ramsay", "Utter garbage");
        classUnderTest.addReview(gordonReview);
        classUnderTest.addReview(gordonReview);
        assert(classUnderTest.stars == 1);
    }

}
