/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void linterTest() {
        App classUnderTest = new App();
        System.out.println(classUnderTest.linter("C:\\Users\\Kevin LaMarca\\Documents\\401 Java\\java-fundamentals\\linter\\app\\src\\linterTest.js"));
    }
}
